// Generated by scripts/extract_schedule.py from LXA Wait Duty Fall 2026 - Wait Duty Schedule.pdf. Do not edit by hand.
window.SCHEDULE = {
  "title": "LXA Wait Duty - Fall 2026",
  "floors": [
    "Third Floor",
    "Second Floor",
    "First Floor / Basement / Outside"
  ],
  "days": [
    {
      "date": "2026-09-23",
      "assignments": {
        "Third Floor": "Zaki Ahmad",
        "Second Floor": "Ezra Mellor",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-09-24",
      "assignments": {
        "Third Floor": "Hunter Greenspan",
        "Second Floor": "David Herzberger",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-09-25",
      "assignments": {
        "Third Floor": "Samuel Kiesel",
        "Second Floor": "Klay Illhart",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-09-26",
      "assignments": {
        "Third Floor": "Camden Venator",
        "Second Floor": "Sasha Kasher",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-09-27",
      "assignments": {
        "Third Floor": "Noah Cohen",
        "Second Floor": "Quinton Baldis",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-09-28",
      "assignments": {
        "Third Floor": "Moksh Patel",
        "Second Floor": "Will Sharpe",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-09-29",
      "assignments": {
        "Third Floor": "Everet Roy",
        "Second Floor": "David Stelk",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-09-30",
      "assignments": {
        "Third Floor": "Patrick Salinas",
        "Second Floor": "Rafael Corral",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-10-01",
      "assignments": {
        "Third Floor": "Tyler Certo",
        "Second Floor": "Elliot James",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-10-02",
      "assignments": {
        "Third Floor": "Jackson Strine",
        "Second Floor": "Daniel Khine",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-10-03",
      "assignments": {
        "Third Floor": "Ethan Zuckerman",
        "Second Floor": "Jack Spillner",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-10-04",
      "assignments": {
        "Third Floor": "Ethan Kim",
        "Second Floor": "Sam Conklin",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-10-05",
      "assignments": {
        "Third Floor": "Matteo Bianchi",
        "Second Floor": "Ned Shapiro",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-10-06",
      "assignments": {
        "Third Floor": "Dylan Gutowski",
        "Second Floor": "Michael Dogue",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-10-07",
      "assignments": {
        "Third Floor": "David Kosyakovskiy",
        "Second Floor": "Ryan Morehead",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-10-08",
      "assignments": {
        "Third Floor": "Kaden Schroeder",
        "Second Floor": "Jack Eisenbrown",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-10-09",
      "assignments": {
        "Third Floor": "Lucas Llovera",
        "Second Floor": "Matthew Walker",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-10-10",
      "note": "Fall Break - No Wait Duty"
    },
    {
      "date": "2026-10-11",
      "note": "Fall Break - No Wait Duty"
    },
    {
      "date": "2026-10-12",
      "note": "Fall Break - No Wait Duty"
    },
    {
      "date": "2026-10-13",
      "note": "Fall Break - No Wait Duty"
    },
    {
      "date": "2026-10-14",
      "assignments": {
        "Third Floor": "Dale Kim",
        "Second Floor": "Eliot Lee",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-10-15",
      "assignments": {
        "Third Floor": "Tyler Kye",
        "Second Floor": "Benjamin Scali",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-10-16",
      "assignments": {
        "Third Floor": "Aidan Aldea-Lustig",
        "Second Floor": "Ezra Mellor",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-10-17",
      "assignments": {
        "Third Floor": "Ryan Cruz",
        "Second Floor": "David Herzberger",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-10-18",
      "assignments": {
        "Third Floor": "Zaki Ahmad",
        "Second Floor": "Klay Illhart",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-10-19",
      "assignments": {
        "Third Floor": "Hunter Greenspan",
        "Second Floor": "Sasha Kasher",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-10-20",
      "assignments": {
        "Third Floor": "Samuel Kiesel",
        "Second Floor": "Quinton Baldis",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-10-21",
      "assignments": {
        "Third Floor": "Camden Venator",
        "Second Floor": "Will Sharpe",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-10-22",
      "assignments": {
        "Third Floor": "Noah Cohen",
        "Second Floor": "David Stelk",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-10-23",
      "assignments": {
        "Third Floor": "Moksh Patel",
        "Second Floor": "Rafael Corral",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-10-24",
      "assignments": {
        "Third Floor": "Everet Roy",
        "Second Floor": "Elliot James",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-10-25",
      "assignments": {
        "Third Floor": "Patrick Salinas",
        "Second Floor": "Daniel Khine",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-10-26",
      "assignments": {
        "Third Floor": "Tyler Certo",
        "Second Floor": "Jack Spillner",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-10-27",
      "assignments": {
        "Third Floor": "Jackson Strine",
        "Second Floor": "Sam Conklin",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-10-28",
      "assignments": {
        "Third Floor": "Ethan Zuckerman",
        "Second Floor": "Ned Shapiro",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-10-29",
      "assignments": {
        "Third Floor": "Ethan Kim",
        "Second Floor": "Michael Dogue",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-10-30",
      "assignments": {
        "Third Floor": "Matteo Bianchi",
        "Second Floor": "Ryan Morehead",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-10-31",
      "assignments": {
        "Third Floor": "Dylan Gutowski",
        "Second Floor": "Jack Eisenbrown",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-11-01",
      "assignments": {
        "Third Floor": "David Kosyakovskiy",
        "Second Floor": "Matthew Walker",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-11-02",
      "assignments": {
        "Third Floor": "Kaden Schroeder",
        "Second Floor": "Eliot Lee",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-11-03",
      "assignments": {
        "Third Floor": "Lucas Llovera",
        "Second Floor": "Benjamin Scali",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-11-04",
      "assignments": {
        "Third Floor": "Dale Kim",
        "Second Floor": "Ezra Mellor",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-11-05",
      "assignments": {
        "Third Floor": "Tyler Kye",
        "Second Floor": "David Herzberger",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-11-06",
      "assignments": {
        "Third Floor": "Aidan Aldea-Lustig",
        "Second Floor": "Klay Illhart",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-11-07",
      "assignments": {
        "Third Floor": "Ryan Cruz",
        "Second Floor": "Sasha Kasher",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-11-08",
      "assignments": {
        "Third Floor": "Zaki Ahmad",
        "Second Floor": "Quinton Baldis",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-11-09",
      "assignments": {
        "Third Floor": "Hunter Greenspan",
        "Second Floor": "Will Sharpe",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-11-10",
      "assignments": {
        "Third Floor": "Samuel Kiesel",
        "Second Floor": "David Stelk",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-11-11",
      "assignments": {
        "Third Floor": "Camden Venator",
        "Second Floor": "Rafael Corral",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-11-12",
      "assignments": {
        "Third Floor": "Noah Cohen",
        "Second Floor": "Elliot James",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-11-13",
      "assignments": {
        "Third Floor": "Moksh Patel",
        "Second Floor": "Daniel Khine",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-11-14",
      "assignments": {
        "Third Floor": "Everet Roy",
        "Second Floor": "Jack Spillner",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-11-15",
      "assignments": {
        "Third Floor": "Patrick Salinas",
        "Second Floor": "Sam Conklin",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-11-16",
      "assignments": {
        "Third Floor": "Tyler Certo",
        "Second Floor": "Ned Shapiro",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-11-17",
      "assignments": {
        "Third Floor": "Jackson Strine",
        "Second Floor": "Michael Dogue",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-11-18",
      "assignments": {
        "Third Floor": "Ethan Zuckerman",
        "Second Floor": "Ryan Morehead",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-11-19",
      "assignments": {
        "Third Floor": "Ethan Kim",
        "Second Floor": "Jack Eisenbrown",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-11-20",
      "assignments": {
        "Third Floor": "Matteo Bianchi",
        "Second Floor": "Matthew Walker",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-11-21",
      "assignments": {
        "Third Floor": "Dylan Gutowski",
        "Second Floor": "Eliot Lee",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-11-22",
      "assignments": {
        "Third Floor": "David Kosyakovskiy",
        "Second Floor": "Benjamin Scali",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-11-23",
      "assignments": {
        "Third Floor": "Kaden Schroeder",
        "Second Floor": "Ezra Mellor",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-11-24",
      "assignments": {
        "Third Floor": "Lucas Llovera",
        "Second Floor": "David Herzberger",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-11-25",
      "note": "Thanksgiving Break - No Wait Duty"
    },
    {
      "date": "2026-11-26",
      "note": "Thanksgiving Break - No Wait Duty"
    },
    {
      "date": "2026-11-27",
      "note": "Thanksgiving Break - No Wait Duty"
    },
    {
      "date": "2026-11-28",
      "note": "Thanksgiving Break - No Wait Duty"
    },
    {
      "date": "2026-11-29",
      "note": "Thanksgiving Break - No Wait Duty"
    },
    {
      "date": "2026-11-30",
      "assignments": {
        "Third Floor": "Dale Kim",
        "Second Floor": "Klay Illhart",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-12-01",
      "assignments": {
        "Third Floor": "Tyler Kye",
        "Second Floor": "Sasha Kasher",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-12-02",
      "assignments": {
        "Third Floor": "Aidan Aldea-Lustig",
        "Second Floor": "Quinton Baldis",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-12-03",
      "assignments": {
        "Third Floor": "Ryan Cruz",
        "Second Floor": "Will Sharpe",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-12-04",
      "assignments": {
        "Third Floor": "Zaki Ahmad",
        "Second Floor": "David Stelk",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-12-05",
      "assignments": {
        "Third Floor": "Hunter Greenspan",
        "Second Floor": "Rafael Corral",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-12-06",
      "assignments": {
        "Third Floor": "Samuel Kiesel",
        "Second Floor": "Elliot James",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-12-07",
      "assignments": {
        "Third Floor": "Camden Venator",
        "Second Floor": "Daniel Khine",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-12-08",
      "assignments": {
        "Third Floor": "Noah Cohen",
        "Second Floor": "Jack Spillner",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-12-09",
      "assignments": {
        "Third Floor": "Moksh Patel",
        "Second Floor": "Sam Conklin",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-12-10",
      "assignments": {
        "Third Floor": "Everet Roy",
        "Second Floor": "Ned Shapiro",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    },
    {
      "date": "2026-12-11",
      "assignments": {
        "Third Floor": "Patrick Salinas",
        "Second Floor": "Michael Dogue",
        "First Floor / Basement / Outside": "Leonel Cerda"
      }
    },
    {
      "date": "2026-12-12",
      "assignments": {
        "Third Floor": "Tyler Certo",
        "Second Floor": "Ryan Morehead",
        "First Floor / Basement / Outside": "Reece Beaty"
      }
    },
    {
      "date": "2026-12-13",
      "assignments": {
        "Third Floor": "Jackson Strine",
        "Second Floor": "Jack Eisenbrown",
        "First Floor / Basement / Outside": "Julian Seidenberg"
      }
    },
    {
      "date": "2026-12-14",
      "assignments": {
        "Third Floor": "Ethan Zuckerman",
        "Second Floor": "Matthew Walker",
        "First Floor / Basement / Outside": "Itash Ram"
      }
    },
    {
      "date": "2026-12-15",
      "assignments": {
        "Third Floor": "Ethan Kim",
        "Second Floor": "Eliot Lee",
        "First Floor / Basement / Outside": "Eli Zucker"
      }
    },
    {
      "date": "2026-12-16",
      "assignments": {
        "Third Floor": "Matteo Bianchi",
        "Second Floor": "Benjamin Scali",
        "First Floor / Basement / Outside": "Marcus Tursonoff"
      }
    },
    {
      "date": "2026-12-17",
      "assignments": {
        "Third Floor": "Dylan Gutowski",
        "Second Floor": "Ezra Mellor",
        "First Floor / Basement / Outside": "Nico Harvey"
      }
    },
    {
      "date": "2026-12-18",
      "assignments": {
        "Third Floor": "David Kosyakovskiy",
        "Second Floor": "David Herzberger",
        "First Floor / Basement / Outside": "Ethan Li"
      }
    },
    {
      "date": "2026-12-19",
      "assignments": {
        "Third Floor": "Kaden Schroeder",
        "Second Floor": "Klay Illhart",
        "First Floor / Basement / Outside": "Finn Davi"
      }
    }
  ]
};
