"""Regenerate schedule.js from the wait duty PDF.

Usage: python scripts/extract_schedule.py "LXA Wait Duty Fall 2026 - Wait Duty Schedule.pdf"
Requires: pip install pypdf

The PDF's positional layout is unreliable, but its content stream lists each
row in order: date, weekday, then either three names (Third, Second, First
floor) or a single note like "Fall Break - No Wait Duty".
"""
import json
import re
import sys
from datetime import datetime
from pathlib import Path

from pypdf import PdfReader

FLOORS = ["Third Floor", "Second Floor", "First Floor / Basement / Outside"]
DATE_RE = re.compile(r"^[A-Z][a-z]{2} \d{1,2}, \d{4}$")


def extract_rows(pdf_path):
    tokens = []
    for page in PdfReader(pdf_path).pages:
        page.extract_text(visitor_text=lambda t, *_: t.strip() and tokens.append(t.strip()))

    rows, current = [], None
    for tok in tokens:
        if DATE_RE.match(tok):
            current = [tok]
            rows.append(current)
        elif current is not None:
            current.append(tok)

    days = []
    for date_str, weekday, *rest in rows:
        date = datetime.strptime(date_str, "%b %d, %Y").date()
        if date.strftime("%A") != weekday:
            sys.exit(f"Weekday mismatch on {date_str}: PDF says {weekday}")
        if len(rest) == len(FLOORS):
            days.append({"date": date.isoformat(), "assignments": dict(zip(FLOORS, rest))})
        elif len(rest) == 1:
            days.append({"date": date.isoformat(), "note": rest[0]})
        else:
            sys.exit(f"Unexpected row shape on {date_str}: {rest}")
    return days


def main():
    pdf_path = Path(sys.argv[1] if len(sys.argv) > 1 else "LXA Wait Duty Fall 2026 - Wait Duty Schedule.pdf")
    days = extract_rows(pdf_path)
    out = Path(__file__).resolve().parent.parent / "schedule.js"
    data = {"title": "LXA Wait Duty - Fall 2026", "floors": FLOORS, "days": days}
    out.write_text(
        f"// Generated by scripts/extract_schedule.py from {pdf_path.name}. Do not edit by hand.\n"
        f"window.SCHEDULE = {json.dumps(data, indent=2)};\n",
        encoding="utf-8",
    )
    names = {n for d in days for n in d.get("assignments", {}).values()}
    print(f"Wrote {out.name}: {len(days)} days, {len(names)} people")


if __name__ == "__main__":
    main()
